travis:
  secure:
    BINSTAR_TOKEN: CxufJiBEVbfq3Lv71YbUc+ZwO3iPtbgSf++sR3TsdbRBsTWPwEIGGHZ2obBo6Qe1CvmFWYe0CKTR24sh9IWSVWhbwoIINdaO9AW0tlZ4W7MuWKSPByHGnmbQEegt3kOF9LOJvLK2vpjmhxoWwBXtTsM5artb1Wx1LlvkF/6oRrBHFJjW49gHAyS7Jb69pBBsbQYSaOm02fJCQZlBenSNuAIj4/y85uNX/rOKwokB5Rz43RslBpHtT3sq7KKfnDiYZ8iLupvB+QIXeUZ46XFjv4j/A2BUekuRulhyYR0QdXD3zxfTNMTpHem7h7ybbQwQ0alINjwfgSI7UGhRDQlMS4U+UPyKP9JIt3YwnFF9rdfUh6SlylytXd5JZ84R2OqehOsXEVWR/+RLrdtTiaZ49OkL7NHwK8P7xRlmoc4e4xo+L1UICk2ptwd52aLgCOC5DLB1K/IN+pkny0rZ7exEClk5mqaV5mrEDioIYNX4LLNwFpGDLf6xkKGyzP/kk2oYzUCXx/tTYY2HGGIK5BJ8j5DJeT180yGQnuvsOVWZsn+p1veVg9jYV7rjRycjPJJRnA1h0ymnBuziGcSOBVgZ/EGrdcI1VG2hTYFYkAEm27Bh9tKzKY285Y/OCpqrxvb8FS5vJZj6nWNUHofY12zaYafWtpfgH9R+Iwp8v1C42u4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
